run:
  timeout: 60m
  modules-download-mode: vendor

issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - govet
    - typecheck
    - unconvert
    - staticcheck
    - gosimple
    # TODO: Enable addition linters
    # - deadcode
    - errcheck
    - ineffassign
    - unused

linters-settings:
  errcheck:
    ignore: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema:ForceNew|Set,fmt:.*,io:Close
  nakedret:
    max-func-lines: 40
  govet:
    disable:
    - printf
