name: Tests

# Runs unit and acceptance tests for pull requests and pushes to main.

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit:
    # Runs `go vet` and unit tests.
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x, 1.17.x]

    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: make vet
        run: make vet

      - name: make test
        run: make test

  acceptance:
    # Runs the acceptance test suite using the `Acceptance Tests` environment.
    # The enviroment should be configured to require reviewers approve the
    # step. This allows the tests to be added as a check to PRs.
    #
    # This job has the `continue-on-error` set to true which prevents blocking
    # PRs if the tests fail.
    needs: unit
    runs-on: ubuntu-latest
    environment:
      name: Acceptance Tests

    concurrency: acceptance_tests

    continue-on-error: true

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Checkout
        uses: actions/checkout@v2

      - name: make testacc
        run: make testacc
        env:
          TESTARGS: -parallel 20
          DIGITALOCEAN_TOKEN: ${{ secrets.ACCEPTANCE_TESTS_TOKEN }}
          SPACES_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }}
          SPACES_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}
